version: '3'
services:
  harbor:
    container_name: harbor
    image: goharbor/harbor:v2.3.0  # Replace with the desired Harbor version
    ports:
      - 80:80
      - 443:443
      - 4443:4443
      - 4444:4444
    volumes:
      - /data/harbor/database:/var/lib/registry/database
      - /data/harbor/registry:/var/lib/registry
      - /data/harbor/chartmuseum:/var/lib/chartmuseum
      - /data/harbor/jobservice:/var/lib/jobservice
      - /data/harbor/clair:/var/lib/clair
      - /data/harbor/notary:/var/lib/notary
    restart: always
